### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by soetakara** [soetakara/furima-36189#21]
■URL
https://furima-36189.herokuapp.com/

■BASIC
・ID
ENJOYfurima
・パスワード
123456

■出品者
・メールアドレス
nagi@docomo
・パスワード
123456a

■購入者
・メールアドレス
takagi@docomo
・パスワード
123456a

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/62644781/144152878-cb069d65-501e-45ae-89e0-41c33fe2d150.png)
